version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000-5001:5000"
    volumes:
      - logs:/app/logs
    networks:
      - app-network
    deploy:
      replicas: 2

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    networks:
      - app-network

volumes:
  logs:

networks:
  app-network:
